# ur5py
Need to install ur_rtde == 1.4.2 which is compatible with the current version of the controller on ur5: potential reason of error "unable to start synchronization"

Error Msg: "Register taken or whatever."
Potential Solution: "Disable Ethernet/Proficient setting" or restart the terminal.
